[package]
name = "space"
version = "0.1.0"
authors = ["Nikita <nikitaab98@gmail.com>"]
description="A high performance multi-threaded ECS game server , written in Rust."
homepage="https://maniastudios.com/"
license-file="LICENSE"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bevy = {version= "0.4"}
bevy_rapier3d = {version= "0.8" , features = [ "simd-stable", "parallel" ]}

serde = {version= "1.0"}
serde_json = {version= "1.0"}

bevy_networking_turbulence = "0.2.0"
bincode = "1.3.2"
